var elamite_map={
 "name": "elamitemap",
 "header":"elamite Dictionary",
"show":{
"toolbar":true,
"footer":true
},
"columns":[
{"field":"script","caption":"Script","sortable":true,"resizable":true,"size":"20%","style":"font-family:elamite"},
{"field":"transliteration","caption":"Transliteration","sortable":true,"resizable":true,"size":"20%"},
{"field":"charName","caption":"SignName","sortable":true,"resizable":true,"size":"20%"},
{"field":"meaning","caption":"Meaning","sortable":true,"resizable":true,"size":"20%",
    render:function(record){
        if(record.concept!=undefined && record.concept!=""){
            return "<a href=\""+record.concept+"\" target=\"_blank\">"+record.meaning+"</a>"
        }else{
            return record.meaning;
        }
}},
{"field":"got","caption":"Gottstein","sortable":true,"resizable":true,"size":"20%"},
{"field":"MesZL","caption":"MesZL","sortable":true,"resizable":true,"size":"20%"},
{"field":"aBZL","caption":"aBZL","sortable":true,"resizable":true,"size":"20%"},
{"field":"HethZL","caption":"HethZL","sortable":true,"resizable":true,"size":"20%"},
{"field":"LHA","caption":"LHA","sortable":true,"resizable":true,"size":"20%"}
]
,"records":[
{ "recid":0, "got":"a1b4c7", "charName":"BÍL (GIBIL; NE×PAB, NE-šeššig)", "MesZL":"312","aBZL":"117","LHA":"173","HethZL":"172","concept":"null", "meaning":"new", "transliteration":"BIL2","script":"𒉋"},
{ "recid":1, "got":"a1b1c1d1", "charName":"AN", "MesZL":"10","aBZL":"9","LHA":"13","HethZL":"8","concept":"https://www.wikidata.org/entity/Q178885", "meaning":"god", "transliteration":"DINGIR","script":"𒀭"},
{ "recid":2, "got":"a1", "charName":"DIŠ (1)", "MesZL":"748","aBZL":"390","LHA":"480","HethZL":"356","concept":"https://www.wikidata.org/wiki/Q177053", "meaning":"mister", "transliteration":"DISZ","script":"𒁹"},
{ "recid":3, "got":"a1b2", "charName":"GIŠ (GEŠ)", "MesZL":"469","aBZL":"160","LHA":"296","HethZL":"178","concept":"null", "meaning":"Non-metallic object", "transliteration":"GISZ","script":"𒄑"},
{ "recid":4, "concept":"null", "meaning":"plural marker", "transliteration":"MESZ","script":"𒈨𒌍"},
{ "recid":5, "concept":"https://www.wikidata.org/entity/Q22731", "meaning":"stone", "transliteration":"NA4","script":"𒉌𒌓"},
{ "recid":6, "got":"a1b1c1d1", "charName":"AN", "MesZL":"10","aBZL":"9","LHA":"13","HethZL":"8","concept":"https://www.wikidata.org/entity/Q178885", "meaning":"city", "transliteration":"URU","script":"𒀭"},
{ "recid":7, "got":"a3", "charName":"A", "MesZL":"839","aBZL":"470","LHA":"579","HethZL":"364; 365","transliteration":"a","script":"𒀀"},
{ "recid":8, "got":"a1b10", "charName":"AG", "MesZL":"127","aBZL":"52","LHA":"97","HethZL":"81","transliteration":"ak","script":"𒀝"},
{ "recid":9, "got":"a1b2c4d1", "charName":"AM (GU4×KUR)", "MesZL":"309","aBZL":"119","LHA":"170","HethZL":"168","concept":"null", "meaning":"now", "transliteration":"am","script":"𒄠"},
{ "recid":10, "got":"a1b1c1d1", "charName":"AN", "MesZL":"10","aBZL":"9","LHA":"13","HethZL":"8","transliteration":"an","script":"𒀭"},
{ "recid":11, "got":"a1b2c1d1", "charName":"AB", "MesZL":"223","aBZL":"125","LHA":"128","HethZL":"97","transliteration":"ap","script":"𒀊"},
{ "recid":12, "got":"a4b2c2", "charName":"AR (IGI.RI)", "MesZL":"726","aBZL":"234","LHA":"451","HethZL":"289","transliteration":"ar","script":"𒅈"},
{ "recid":13, "got":"a14b9c2d2", "charName":"AZ (PIRIG×ZA)", "MesZL":"297","aBZL":"180","LHA":"131","HethZL":"92","transliteration":"as","script":"𒊍"},
{ "recid":14, "got":"b1", "charName":"AŠ", "MesZL":"1","aBZL":"1","LHA":"1","HethZL":"1","transliteration":"asz","script":"𒀸"},
{ "recid":15, "got":"a3b4c1d1", "charName":"AD", "MesZL":"258","aBZL":"132","LHA":"145","HethZL":"105","transliteration":"at","script":"𒀜"},
{ "recid":16, "got":"a1b1c1d1", "charName":"BA", "MesZL":"14","aBZL":"303","LHA":"5","HethZL":"205","transliteration":"ba","script":"𒁀"},
{ "recid":17, "got":"a1b1", "charName":"BAR", "MesZL":"121","aBZL":"57","LHA":"74","HethZL":"20","transliteration":"bar","script":"𒁇"},
{ "recid":18, "got":"b1c1d1", "charName":"BAD", "MesZL":"113","aBZL":"25","LHA":"69","HethZL":"13","concept":"http://lemon-model.net/lexica/uby/vn/VN_LexicalEntry_2922", "meaning":"create", "transliteration":"be","script":"𒁁"},
{ "recid":19, "got":"a2b1c1d1", "charName":"MUG", "MesZL":"12","aBZL":"12","LHA":"3","HethZL":"22","transliteration":"buk","script":"𒈮"},
{ "recid":20, "got":"a1b1c1d1", "charName":"AN", "MesZL":"10","aBZL":"9","LHA":"13","HethZL":"8","concept":"https://www.wikidata.org/wiki/Q190", "meaning":"god", "transliteration":"d","script":"𒀭"},
{ "recid":21, "got":"a2b8c1", "charName":"DA", "MesZL":"561","aBZL":"229","LHA":"335","HethZL":"214","transliteration":"da","script":"𒁕"},
{ "recid":22, "got":"a1b2c2", "charName":"DU", "MesZL":"350","aBZL":"64, 197","LHA":"206","HethZL":"128","concept":"http://lemon-model.net/lexica/uby/vn/VN_LexicalEntry_2756", "meaning":"receive", "transliteration":"du","script":"𒁺"},
{ "recid":23, "got":"a2b5c3", "charName":"EN", "MesZL":"164","aBZL":"62","LHA":"99","HethZL":"40","transliteration":"en","script":"𒂗"},
{ "recid":24, "got":"c2", "charName":"GAM", "MesZL":"576","aBZL":"359","LHA":"362","HethZL":"247","transliteration":"gam","script":"𒃵"},
{ "recid":25, "got":"a4c2", "charName":"ḪA (KU6)", "MesZL":"856","aBZL":"475","LHA":"589","HethZL":"367","transliteration":"ha","script":"𒄩"},
{ "recid":26, "got":"b1c1d1", "charName":"ḪAL", "MesZL":"3","aBZL":"7","LHA":"2","HethZL":"2","transliteration":"hal","script":"𒄬"},
{ "recid":27, "got":"a1b4c2d2", "charName":"ḪAR (ḪI×ÁŠ)", "MesZL":"644","aBZL":"281","LHA":"401","HethZL":"333","transliteration":"har","script":"𒄯"},
{ "recid":28, "got":"a1c2", "charName":"TAR", "MesZL":"9","aBZL":"231","LHA":"12","HethZL":"7","transliteration":"haz","script":"𒋻"},
{ "recid":29, "got":"c2d2", "charName":"ḪI (DÙG)", "MesZL":"631","aBZL":"277","LHA":"396","HethZL":"335","transliteration":"hi","script":"𒄭"},
{ "recid":30, "got":"a2b1c1", "charName":"ḪU", "MesZL":"132","aBZL":"34","LHA":"78","HethZL":"24","transliteration":"hu","script":"𒄷"},
{ "recid":31, "got":"a3b6c2", "charName":"IG (GÁL)", "MesZL":"136","aBZL":"61","LHA":"80","HethZL":"67","transliteration":"ik","script":"𒅅"},
{ "recid":32, "got":"a2c10d1", "charName":"IN", "MesZL":"261","aBZL":"386","LHA":"148","HethZL":"354","transliteration":"in","script":"𒅔"},
{ "recid":33, "got":"a3c1d1", "charName":"IR (GAG-gunû)", "MesZL":"437","aBZL":"263","LHA":"232","HethZL":"77","transliteration":"ir","script":"𒅕"},
{ "recid":34, "got":"a2b4c1", "charName":"IŠ", "MesZL":"357","aBZL":"162","LHA":"212","HethZL":"151","transliteration":"isz","script":"𒅖"},
{ "recid":35, "got":"a3b2c5d1", "charName":"KA", "MesZL":"24","aBZL":"312","LHA":"15","HethZL":"133","transliteration":"ka","script":"𒅗"},
{ "recid":36, "got":"a1c1d1", "charName":"SÌLA", "MesZL":"99","aBZL":"269","LHA":"62","HethZL":"21","transliteration":"ka4","script":"𒋡"},
{ "recid":37, "got":"a2b4c14", "charName":"GAZ (KUM×ŠE)", "MesZL":"340","aBZL":"139","LHA":"192","HethZL":"122","transliteration":"kaz","script":"𒄤"},
{ "recid":38, "got":"b4c2d2", "charName":"KI", "MesZL":"737","aBZL":"432","LHA":"461","HethZL":"313","transliteration":"ke","script":"𒆠"},
{ "recid":39, "got":"b4c2d2", "charName":"KI", "MesZL":"737","aBZL":"432","LHA":"461","HethZL":"313","transliteration":"ki","script":"𒆠"},
{ "recid":40, "got":"a2b3", "charName":"KU (DÚR, TUKUL, TUŠ)", "MesZL":"808","aBZL":"415","LHA":"536","HethZL":"206","transliteration":"ku","script":"𒆪"},
{ "recid":41, "got":"b2c3", "charName":"NUMUN", "MesZL":"117","aBZL":"26","LHA":"72","HethZL":"12","transliteration":"kul","script":"𒆰"},
{ "recid":42, "got":"a2b4c4", "charName":"KUM (GUM)", "MesZL":"339","aBZL":"138","LHA":"191","HethZL":"120","transliteration":"kum","script":"𒄣"},
{ "recid":43, "got":"c3", "charName":"KUR", "MesZL":"578","aBZL":"369","LHA":"366","HethZL":"329","transliteration":"kur","script":"𒆳"},
{ "recid":44, "got":"a5b7", "charName":"LA", "MesZL":"89","aBZL":"177","LHA":"55","HethZL":"95","transliteration":"la","script":"𒆷"},
{ "recid":45, "got":"a2b4c11d1", "charName":"LI", "MesZL":"85","aBZL":"381","LHA":"59","HethZL":"343","concept":"http://lemon-model.net/lexica/uby/vn/VN_LexicalEntry_1857", "meaning":"give", "transliteration":"li","script":"𒇷"},
{ "recid":46, "got":"a1b1c1", "charName":"IGI (ŠI, LIM)", "MesZL":"724","aBZL":"233","LHA":"449","HethZL":"288","concept":"https://www.wikidata.org/entity/Q43016", "meaning":"1000", "transliteration":"lim","script":"𒅆"},
{ "recid":47, "got":"a3b3", "charName":"LU (UDU)", "MesZL":"812","aBZL":"416","LHA":"537","HethZL":"210","transliteration":"lu","script":"𒇻"},
{ "recid":48, "got":"a2b3", "charName":"MA", "MesZL":"552","aBZL":"166","LHA":"342","HethZL":"208","transliteration":"ma","script":"𒈠"},
{ "recid":49, "got":"a1b1", "charName":"MAŠ", "MesZL":"120","aBZL":"29","LHA":"74","HethZL":"20","transliteration":"mas","script":"𒈦"},
{ "recid":50, "got":"a1b1", "charName":"MAŠ", "MesZL":"120","aBZL":"29","LHA":"74","HethZL":"20","transliteration":"masz","script":"𒈦"},
{ "recid":51, "got":"a1b1", "charName":"ME", "MesZL":"753","aBZL":"392","LHA":"532","HethZL":"357","concept":"https://www.wikidata.org/entity/Q37413", "meaning":"100", "transliteration":"me","script":"𒈨"},
{ "recid":52, "got":"a6b8c3", "charName":"MEN (GÁ× ME.EN)", "MesZL":"427","aBZL":"102","LHA":"270","HethZL":"","concept":"https://www.wikidata.org/entity/Q170984", "meaning":"crown", "transliteration":"men","script":"𒃞"},
{ "recid":53, "got":"b8c1", "charName":"MI", "MesZL":"681","aBZL":"348","LHA":"427","HethZL":"267","transliteration":"mi","script":"𒈪"},
{ "recid":54, "got":"b1c6", "charName":"MU", "MesZL":"98","aBZL":"20","LHA":"61","HethZL":"17","transliteration":"mu","script":"𒈬"},
{ "recid":55, "got":"b4c3d2", "charName":"NA", "MesZL":"110","aBZL":"24","LHA":"70","HethZL":"15","transliteration":"na","script":"𒈾"},
{ "recid":56, "got":"a2b2c2d2", "charName":"NAB (ANoverAN)", "MesZL":"246","aBZL":"","LHA":"129","HethZL":"100","concept":"https://www.wikidata.org/entity/Q178885", "meaning":"god", "transliteration":"nap","script":"𒀮"},
{ "recid":57, "got":"a2c1d1", "charName":"NI", "MesZL":"380","aBZL":"261","LHA":"231","HethZL":"72","transliteration":"ni","script":"𒉌"},
{ "recid":58, "got":"a1b1d1", "charName":"NU", "MesZL":"112","aBZL":"19","LHA":"75","HethZL":"11","concept":"https://www.wikidata.org/entity/Q1165897", "meaning":"you", "transliteration":"nu","script":"𒉡"},
{ "recid":59, "concept":"https://www.wikidata.org/entity/Q7478101", "meaning":"we", "transliteration":"nuku","script":"𒉡𒆪"},
{ "recid":60, "got":"a1b2", "charName":"PA", "MesZL":"464","aBZL":"143","LHA":"295","HethZL":"174","transliteration":"pa","script":"𒉺"},
{ "recid":61, "got":"a1b1c2", "charName":"PI", "MesZL":"598","aBZL":"370","LHA":"383","HethZL":"317","transliteration":"pe","script":"𒉿"},
{ "recid":62, "got":"a1b1c2", "charName":"PI", "MesZL":"598","aBZL":"370","LHA":"383","HethZL":"317","concept":"https://www.wikidata.org/entity/Q427923", "meaning":"10000", "transliteration":"pi","script":"𒉿"},
{ "recid":63, "got":"c2d2", "charName":"SIG", "MesZL":"881","aBZL":"437","LHA":"592","HethZL":"255","transliteration":"pik","script":"𒋝"},
{ "recid":64, "got":"b1c2d2", "charName":"BU (GÍD)", "MesZL":"580","aBZL":"265","LHA":"371","HethZL":"339","transliteration":"pu","script":"𒁍"},
{ "recid":65, "got":"a4b5", "charName":"RA", "MesZL":"511","aBZL":"192","LHA":"328","HethZL":"233","transliteration":"ra","script":"𒊏"},
{ "recid":66, "got":"a3b1c1", "charName":"RI", "MesZL":"142","aBZL":"39","LHA":"86","HethZL":"32","transliteration":"ri","script":"𒊑"},
{ "recid":67, "got":"b2c2d2", "charName":"RU", "MesZL":"111","aBZL":"60","LHA":"68","HethZL":"43","transliteration":"ru","script":"𒊒"},
{ "recid":68, "got":"a4b4", "charName":"LUḪ", "MesZL":"494","aBZL":"196","LHA":"321","HethZL":"198","concept":"https://www.wikidata.org/entity/Q8441", "meaning":"man", "transliteration":"ruh","script":"𒈛"},
{ "recid":69, "got":"a4b4", "charName":"SA", "MesZL":"172","aBZL":"147","LHA":"104","HethZL":"200","transliteration":"sa","script":"𒊓"},
{ "recid":70, "got":"a2b2", "charName":"SI", "MesZL":"181","aBZL":"164","LHA":"112","HethZL":"86","transliteration":"si","script":"𒋛"},
{ "recid":71, "got":"a4b1c2d2", "charName":"SUD (BU-gunû)", "MesZL":"584","aBZL":"266","LHA":"373","HethZL":"341","transliteration":"sir","script":"𒋤"},
{ "recid":72, "got":"a5b2c1d1", "charName":"SU", "MesZL":"16","aBZL":"305","LHA":"7","HethZL":"213","transliteration":"su","script":"𒋢"},
{ "recid":73, "got":"c4d1", "charName":"TIL", "MesZL":"","aBZL":"","LHA":"","HethZL":"","transliteration":"sun","script":"𒌀"},
{ "recid":74, "got":"a2b4c1d1", "charName":"ŠA", "MesZL":"566","aBZL":"203","LHA":"353","HethZL":"158","transliteration":"sza","script":"𒊭"},
{ "recid":75, "got":"a3d1", "charName":"NÍG (GAR, NINDA)", "MesZL":"859","aBZL":"473","LHA":"597","HethZL":"369","transliteration":"sza2","script":"𒃻"},
{ "recid":76, "got":"c10", "charName":"ŠE", "MesZL":"579","aBZL":"378","LHA":"367","HethZL":"338","transliteration":"sze","script":"𒊺"},
{ "recid":77, "got":"a1b1c1", "charName":"IGI (ŠI, LIM)", "MesZL":"724","aBZL":"233","LHA":"449","HethZL":"288","transliteration":"szi","script":"𒅆"},
{ "recid":78, "got":"a1b5", "charName":"ŠU", "MesZL":"567","aBZL":"225","LHA":"354","HethZL":"68","transliteration":"szu","script":"𒋗"},
{ "recid":79, "got":"a2b2c1d1", "charName":"TA", "MesZL":"248","aBZL":"123","LHA":"139","HethZL":"160","concept":"http://lemon-model.net/lexica/uby/vn/VN_LexicalEntry_1464", "meaning":"put", "transliteration":"ta","script":"𒋫"},
{ "recid":80, "got":"a6b2c2d2", "charName":"TAG (ŠUM)", "MesZL":"221","aBZL":"122","LHA":"126","HethZL":"91","transliteration":"tak","script":"𒋳"},
{ "recid":81, "got":"a3b1c1", "charName":"RI", "MesZL":"142","aBZL":"39","LHA":"86","HethZL":"32","transliteration":"tal","script":"𒊑"},
{ "recid":82, "got":"c2d2", "charName":"UD (BABBAR)", "MesZL":"596","aBZL":"332","LHA":"381","HethZL":"316","transliteration":"tam","script":"𒌓"},
{ "recid":83, "got":"a2c2d2", "charName":"TE", "MesZL":"589","aBZL":"289","LHA":"376","HethZL":"249","concept":"http://lemon-model.net/lexica/uby/vn/VN_LexicalEntry_3138", "meaning":"prefer", "transliteration":"te","script":"𒋼"},
{ "recid":84, "got":"a1b2c2", "charName":"TI", "MesZL":"118","aBZL":"23","LHA":"73","HethZL":"37","transliteration":"ti","script":"𒋾"},
{ "recid":85, "got":"a1c12d2", "charName":"TU", "MesZL":"86","aBZL":"382","LHA":"58","HethZL":"346","transliteration":"tu","script":"𒌅"},
{ "recid":86, "got":"a1c3d1", "charName":"NIM", "MesZL":"690","aBZL":"355","LHA":"433","HethZL":"74","transliteration":"tum4","script":"𒉏"},
{ "recid":87, "got":"a1b2c2d2", "charName":"TUR (DUMU)", "MesZL":"255","aBZL":"393","LHA":"144","HethZL":"237","transliteration":"tur","script":"𒌉"},
{ "recid":88, "got":"c1", "charName":"U", "MesZL":"661","aBZL":"337","LHA":"411","HethZL":"261","concept":"https://www.wikidata.org/entity/Q49404", "meaning":"I", "transliteration":"u","script":"𒌋"},
{ "recid":89, "got":"a1c2d2", "charName":"UB", "MesZL":"504","aBZL":"288","LHA":"306","HethZL":"152","transliteration":"ub","script":"𒌒"},
{ "recid":90, "got":"a1b2c2d1", "charName":"UL (DU7)", "MesZL":"698","aBZL":"344","LHA":"441","HethZL":"275","transliteration":"ul","script":"𒌌"},
{ "recid":91, "got":"a6b4", "charName":"UM", "MesZL":"238","aBZL":"113","LHA":"134","HethZL":"98","transliteration":"um","script":"𒌝"},
{ "recid":92, "got":"a6b5c2d2", "charName":"UN", "MesZL":"501","aBZL":"169","LHA":"312","HethZL":"197","transliteration":"un","script":"𒌦"},
{ "recid":93, "got":"a3b2c1", "charName":"UŠ (NITA)", "MesZL":"381","aBZL":"68","LHA":"211","HethZL":"132","transliteration":"usz","script":"𒍑"},
{ "recid":94, "got":"c2d2", "charName":"UD (BABBAR)", "MesZL":"596","aBZL":"332","LHA":"381","HethZL":"316","transliteration":"ut","script":"𒌓"},
{ "recid":95, "got":"a2b1c11", "charName":"US", "MesZL":"","aBZL":"","LHA":"","HethZL":"","transliteration":"uz","script":"𒊻"},
{ "recid":96, "got":"a1b1c2", "charName":"PI", "MesZL":"598","aBZL":"370","LHA":"383","HethZL":"317","transliteration":"ya","script":"𒉿"},
{ "recid":97, "got":"a4", "charName":"ZA", "MesZL":"851","aBZL":"474","LHA":"586","HethZL":"366","transliteration":"za","script":"𒍝"},
{ "recid":98, "got":"a5b1c1d1", "charName":"ZU", "MesZL":"15","aBZL":"304","LHA":"6","HethZL":"209","transliteration":"zu","script":"𒍪"}]}