var luwiancn_map={
 "name": "luwiancn",
 "header":"luwiancn Dictionary",
"show":{
"toolbar":true,
"footer":true
},
"columns":[
{"field":"script","caption":"Script","sortable":true,"resizable":true,"size":"20%"},
{"field":"transliteration","caption":"Transliteration","sortable":true,"resizable":true,"size":"20%"},
{"field":"charName","caption":"SignName","sortable":true,"resizable":true,"size":"20%"},
{"field":"meaning","caption":"Meaning","sortable":true,"resizable":true,"size":"20%",
    render:function(record){
        if(record.concept!=undefined){
            return "<a href=\""+record.concept+"\" target=\"_blank\">"+record.translation+"</a>"
        }else{
            return record.translation;
        }
}},
{"field":"got","caption":"Gottstein","sortable":true,"resizable":true,"size":"20%"},
{"field":"MesZL","caption":"MesZL","sortable":true,"resizable":true,"size":"20%"},
{"field":"aBZL","caption":"aBZL","sortable":true,"resizable":true,"size":"20%"},
{"field":"HethZL","caption":"HethZL","sortable":true,"resizable":true,"size":"20%"}
]
,"records":[
{ "recid":0, "got":"a3", "charName":"A", "concept":"", "MesZL":"839","aBZL":"470","LHA":"579","HethZL":"364; 365","transliteration":"A","script":"𒀀"},
{ "recid":1, "got":"a1b1c1d1", "charName":"AN", "concept":"https://en.wikipedia.org/wiki/Dingir", "MesZL":"10","aBZL":"9","LHA":"13","HethZL":"8","transliteration":"An","script":"𒀭"},
{ "recid":2, "got":"a4b2c2", "charName":"AR (IGI.RI)", "concept":"", "MesZL":"726","aBZL":"234","LHA":"451","HethZL":"289","transliteration":"Ar","script":"𒅈"},
{ "recid":3, "got":"a1b1c1d1", "charName":"AN", "concept":"https://en.wikipedia.org/wiki/Dingir", "MesZL":"10","aBZL":"9","LHA":"13","HethZL":"8","transliteration":"D","script":"𒀭"},
{ "recid":4, "got":"a1b2", "charName":"GIŠ (GEŠ)", "concept":"", "MesZL":"469","aBZL":"160","LHA":"296","HethZL":"178","transliteration":"GISZ","script":"𒄑"},
{ "recid":5, "got":"a2b4c2", "charName":"GUL (SÚN)", "concept":"", "MesZL":"682","aBZL":"343","LHA":"429","HethZL":"271","transliteration":"Gul","script":"𒄢"},
{ "recid":6, "got":"a2b2", "charName":"GUR", "concept":"", "MesZL":"180","aBZL":"92","LHA":"111","HethZL":"185","transliteration":"Gur","script":"𒄥"},
{ "recid":7, "got":"a4c2", "charName":"ḪA (KU6)", "concept":"", "MesZL":"856","aBZL":"475","LHA":"589","HethZL":"367","transliteration":"Ha","script":"𒄩"},
{ "recid":8, "got":"a8b2c3d2", "charName":"IM", "concept":"", "MesZL":"641","aBZL":"297","LHA":"399","HethZL":"337","transliteration":"Im","script":"𒅎"},
{ "recid":9, "got":"b1c3d2", "charName":"ḪI×BAD", "concept":"", "MesZL":"640","aBZL":"279","LHA":"406v1","HethZL":"355","transliteration":"Kam","script":"𒄰"},
{ "recid":10, "got":"a2b8c1", "charName":"KAB", "concept":"", "MesZL":"148","aBZL":"226","LHA":"88","HethZL":"49","transliteration":"Kap","script":"𒆏"},
{ "recid":11, "got":"a2b4c1d1", "charName":"ŠA", "concept":"", "MesZL":"566","aBZL":"203","LHA":"353","HethZL":"158","transliteration":"Sza","script":"𒊭"},
{ "recid":12, "got":"a2b2c1d1", "charName":"TA", "concept":"", "MesZL":"248","aBZL":"123","LHA":"139","HethZL":"160","transliteration":"Ta","script":"𒋫"},
{ "recid":13, "got":"a3b3", "charName":"URU (IRI)", "concept":"", "MesZL":"71","aBZL":"181","LHA":"38","HethZL":"229","transliteration":"URU","script":"𒌷"},
{ "recid":14, "got":"a2b1c10", "charName":"ZI", "concept":"", "MesZL":"140","aBZL":"41","LHA":"84","HethZL":"33","transliteration":"Zi","script":"𒍣"},
{ "recid":15, "got":"a3", "charName":"A", "concept":"", "MesZL":"839","aBZL":"470","LHA":"579","HethZL":"364; 365","transliteration":"a","script":"𒀀"},
{ "recid":16, "got":"a3b4c1d1", "charName":"AD", "concept":"", "MesZL":"258","aBZL":"132","LHA":"145","HethZL":"105","transliteration":"ad","script":"𒀜"},
{ "recid":17, "transliteration":"al","script":"𒀠"},
{ "recid":18, "got":"a1b1c1d1", "charName":"AN", "concept":"https://en.wikipedia.org/wiki/Dingir", "MesZL":"10","aBZL":"9","LHA":"13","HethZL":"8","transliteration":"an","script":"𒀭"},
{ "recid":19, "got":"a2b8c1", "charName":"DA", "concept":"", "MesZL":"561","aBZL":"229","LHA":"335","HethZL":"214","transliteration":"da","script":"𒁕"},
{ "recid":20, "got":"a1b2c2", "charName":"DU", "concept":"", "MesZL":"350","aBZL":"64, 197","LHA":"206","HethZL":"128","transliteration":"du","script":"𒁺"},
{ "recid":21, "got":"b5", "charName":"I", "concept":"", "MesZL":"252","aBZL":"192","LHA":"142","HethZL":"217","transliteration":"i","script":"𒄿"},
{ "recid":22, "got":"a2b8c7", "charName":"A2", "concept":"", "MesZL":"560","aBZL":"230","LHA":"334","HethZL":"215","transliteration":"id","script":"𒀉"},
{ "recid":23, "got":"a6b2", "charName":"IB", "concept":"", "MesZL":"807","aBZL":"394","LHA":"535","HethZL":"44","transliteration":"ip","script":"𒅁"},
{ "recid":24, "got":"a2b4c1", "charName":"IŠ", "concept":"", "MesZL":"357","aBZL":"162","LHA":"212","HethZL":"151","transliteration":"isz","script":"𒅖"},
{ "recid":25, "got":"a1b2", "charName":"GIŠ (GEŠ)", "concept":"", "MesZL":"469","aBZL":"160","LHA":"296","HethZL":"178","transliteration":"iz","script":"𒄑"},
{ "recid":26, "got":"a2b3", "charName":"KU (DÚR, TUKUL, TUŠ)", "concept":"", "MesZL":"808","aBZL":"415","LHA":"536","HethZL":"206","transliteration":"ku","script":"𒆪"},
{ "recid":27, "got":"a5b7", "charName":"LA", "concept":"", "MesZL":"89","aBZL":"177","LHA":"55","HethZL":"95","transliteration":"la","script":"𒆷"},
{ "recid":28, "got":"a2b4c11d1", "charName":"LI", "concept":"", "MesZL":"85","aBZL":"381","LHA":"59","HethZL":"343","transliteration":"li","script":"𒇷"},
{ "recid":29, "got":"a2b3", "charName":"MA", "concept":"", "MesZL":"552","aBZL":"166","LHA":"342","HethZL":"208","transliteration":"ma","script":"𒈠"},
{ "recid":30, "got":"a2b3", "charName":"MAR", "concept":"", "MesZL":"483","aBZL":"144","LHA":"307","HethZL":"191","transliteration":"mar","script":"𒈥"},
{ "recid":31, "got":"a1b1", "charName":"MAŠ", "concept":"", "MesZL":"120","aBZL":"29","LHA":"74","HethZL":"20","transliteration":"masz","script":"𒈦"},
{ "recid":32, "got":"b4c3d2", "charName":"NA", "concept":"", "MesZL":"110","aBZL":"24","LHA":"70","HethZL":"15","transliteration":"na","script":"𒈾"},
{ "recid":33, "got":"a2c1d1", "charName":"NI", "concept":"", "MesZL":"380","aBZL":"261","LHA":"231","HethZL":"72","transliteration":"ni","script":"𒉌"},
{ "recid":34, "got":"a1b1d1", "charName":"NU", "concept":"", "MesZL":"112","aBZL":"19","LHA":"75","HethZL":"11","transliteration":"nu","script":"𒉡"},
{ "recid":35, "got":"a1b2", "charName":"PA", "concept":"", "MesZL":"464","aBZL":"143","LHA":"295","HethZL":"174","transliteration":"pa","script":"𒉺"},
{ "recid":36, "got":"a4b2c1d1", "charName":"BI", "concept":"", "MesZL":"358","aBZL":"79","LHA":"214","HethZL":"153","transliteration":"pi2","script":"𒁉"},
{ "recid":37, "got":"a4b5", "charName":"RA", "concept":"", "MesZL":"511","aBZL":"192","LHA":"328","HethZL":"233","transliteration":"ra","script":"𒊏"},
{ "recid":38, "got":"a3b1c1", "charName":"RI", "concept":"", "MesZL":"142","aBZL":"39","LHA":"86","HethZL":"32","transliteration":"ri","script":"𒊑"},
{ "recid":39, "got":"b2c2d2", "charName":"RU", "concept":"", "MesZL":"111","aBZL":"60","LHA":"68","HethZL":"43","transliteration":"ru","script":"𒊒"},
{ "recid":40, "got":"a2b4c1d1", "charName":"ŠA", "concept":"", "MesZL":"566","aBZL":"203","LHA":"353","HethZL":"158","transliteration":"sza","script":"𒊭"},
{ "recid":41, "got":"a2b2c9", "charName":"SAR", "concept":"", "MesZL":"541","aBZL":"385","LHA":"331e, 152iv","HethZL":"353","transliteration":"szar","script":"𒊬"},
{ "recid":42, "got":"c10", "charName":"ŠE", "concept":"", "MesZL":"579","aBZL":"378","LHA":"367","HethZL":"338","transliteration":"sze","script":"𒊺"},
{ "recid":43, "got":"a1b1c1", "charName":"IGI (ŠI, LIM)", "concept":"", "MesZL":"724","aBZL":"233","LHA":"449","HethZL":"288","transliteration":"szi","script":"𒅆"},
{ "recid":44, "got":"a2b2c1d1", "charName":"TA", "concept":"", "MesZL":"248","aBZL":"123","LHA":"139","HethZL":"160","transliteration":"ta","script":"𒋫"},
{ "recid":45, "got":"a1c2", "charName":"TAR", "concept":"", "MesZL":"9","aBZL":"231","LHA":"12","HethZL":"7","transliteration":"tar","script":"𒋻"},
{ "recid":46, "got":"c1", "charName":"U", "concept":"", "MesZL":"661","aBZL":"337","LHA":"411","HethZL":"261","transliteration":"u","script":"𒌋"},
{ "recid":47, "got":"a4b2", "charName":"Ú", "concept":"", "MesZL":"490","aBZL":"146","LHA":"318","HethZL":"195","transliteration":"u2","script":"𒌑"},
{ "recid":48, "got":"a1c2d2", "charName":"UB", "concept":"", "MesZL":"504","aBZL":"288","LHA":"306","HethZL":"152","transliteration":"up","script":"𒌒"},
{ "recid":49, "got":"a3b2c1", "charName":"UŠ (NITA)", "concept":"", "MesZL":"381","aBZL":"68","LHA":"211","HethZL":"132","transliteration":"usz","script":"𒍑"},
{ "recid":50, "got":"a1b1c2", "charName":"PI", "concept":"", "MesZL":"598","aBZL":"370","LHA":"383","HethZL":"317","transliteration":"wa","script":"𒉿"},
{ "recid":51, "got":"a1b1c2", "charName":"PI", "concept":"", "MesZL":"598","aBZL":"370","LHA":"383","HethZL":"317","transliteration":"ya","script":"𒉿"},
{ "recid":52, "got":"a4", "charName":"ZA", "concept":"", "MesZL":"851","aBZL":"474","LHA":"586","HethZL":"366","transliteration":"za","script":"𒍝"},
{ "recid":53, "got":"a5b1c1d1", "charName":"ZU", "concept":"", "MesZL":"15","aBZL":"304","LHA":"6","HethZL":"209","transliteration":"zu","script":"𒍪"}]}