var paleocode=[{"cunei":"𒀀", "codepoint":"U+12000", "translit":"A", "borger":"839","paleocode":"a-a:a"},
{"cunei":"𒀁", "codepoint":"U+12001", "translit":"A x A", "borger":"845", "paleocode":"a-a-a:a-a:a"},
{"cunei":"𒀂", "codepoint":"U+12002", "translit":"A x BAD", "borger":"840", "paleocode":"a-b-w-a:a"},
{"cunei":"𒋰", "codepoint":"U+122F0", "translit":"TAB", "borger":"209","paleocode":"b:b"},
{"cunei":"𒌑", "codepoint":"U+12311", "translit":"U2", "borger":"490","paleocode":"B::B-a-a-a-a"},
{"cunei":"𒀾", "codepoint":"U+1203E", "translit":"AŠ2", "borger":"548","paleocode":"b:b:b:b-a"},
{"cunei":"𒇲", "codepoint":"U+121F2", "translit":"LAL", "borger":"750","paleocode":"a-b"},
{"cunei":"𒁇", "codepoint":"U+12047", "translit":"BAR", "borger":"121","paleocode":";b-a"},
{"cunei":"𒂃", "codepoint":"U+12083", "translit":"DUḪ", "borger":"298", "paleocode":"b:b_w:w-w:w-w:w-w:w"},
{"cunei":"𒂉", "codepoint":"U+12089", "translit":"DUR2", "borger":"808","paleocode":"a-b;b-::b_a"},
{"cunei":"𒃲", "codepoint":"U+120F2", "translit":"GAL", "borger":"553","paleocode":"b:b:b:b_a-:b"},
{"cunei":"𒇹", "codepoint":"U+121F9", "translit":"LIMMU2", "borger":"215","paleocode":"b:b_b:b"},
{"cunei":"𒄩", "codepoint":"U+12129", "translit":"ḪA", "borger":"856","paleocode":"a:a;w-a:a-w"},
{"cunei":"𒆳", "codepoint":"U+121B3", "translit":"KUR", "borger":"578","paleocode":"w:w-w"},
{"cunei":"𒈦", "codepoint":"U+12226", "translit":"MAŠ", "borger":"120","paleocode":":b-a"},
{"cunei":"𒆜", "codepoint":"U+1219C", "translit":"KASKAL", "borger":"302","paleocode":"c:d-d:c"},
{"cunei":"𒆕", "codepoint":"U+12195", "translit":"KAK", "borger":"379","paleocode":"a-c:d"},
{"cunei":"𒆚", "codepoint":"U+1219A", "translit":"KAM2", "borger":"595","paleocode":"c:c-c:c:c-c"},
{"cunei":"𒈛", "codepoint":"U+1221B", "translit":"LUḪ", "borger":"494","paleocode":"b:b:b:b_a-a-a-a"},
{"cunei":"𒈠", "codepoint":"U+12220", "translit":"MA", "borger":"552","paleocode":"b_a;b-:b_a"},
{"cunei":"𒉡", "codepoint":"U+12261", "translit":"NU", "borger":"112","paleocode":":B-A;d"},
{"cunei":"𒀫", "codepoint":"U+1202B", "translit":"AMAR", "borger":"695","paleocode":"w:w_b:b_w:w"},
{"cunei":"𒃵", "codepoint":"U+120F5", "translit":"GAM", "borger":"576","paleocode":"c.c"},
{"cunei":"𒊸", "codepoint":"U+122B8", "translit":"ŠAB6", "paleocode":"b:b_b:b:b_:b"},
{"cunei":"𒄑", "codepoint":"U+12111", "translit":"GIŠ", "borger":"469","paleocode":"b::b_a"},
{"cunei":"𒄨", "codepoint":"U+12128", "translit":"GURUŠ", "paleocode":"b:::b-a--a"},
{"cunei":"𒄷", "codepoint":"U+12137", "translit":"ḪU", "borger":"132","paleocode":":b-a-::w-a"},
{"cunei":"𒄿", "codepoint":"U+1213F", "translit":"I", "borger":"252","paleocode":"b:b:b_/b:b"},
{"cunei":"𒈨", "codepoint":"U+12228", "translit":"ME", "borger":"753","paleocode":"a-:b"},
{"cunei":"𒈫", "codepoint":"U+1222B", "translit":"MIN", "borger":"825","paleocode":"a-a"},
{"cunei":"𒋙", "codepoint":"U+122D9", "translit":"ŠU2", "borger":"869","paleocode":"a;w"},
{"cunei":"𒌷", "codepoint":"U+12337", "translit":"URU", "borger":"071","paleocode":"::b::b-a--a"},
{"cunei":"𒍝", "codepoint":"U+1235D", "translit":"ZA", "borger":"851","paleocode":"a::a-a::a"},
{"cunei":"𒀸", "codepoint":"U+12038", "translit":"AŠ", "borger":"001","paleocode":"b"},
{"cunei":"𒁹", "codepoint":"U+12079", "translit":"DIŠ", "borger":"748","paleocode":"a"},
{"cunei":"𒄐", "codepoint":"U+12110", "translit":"GISAL", "borger":"376","paleocode":"b;b_a:c:::d_b;b_a"},
{"cunei":"𒄬", "codepoint":"U+1212C", "translit":"ḪAL", "borger":"003","paleocode":"bc:d"},
{"cunei":"𒃻", "codepoint":"U+120FB", "translit":"GAR", "borger":"859","paleocode":"a-a-a;f"},
{"cunei":"𒅀", "codepoint":"U+12140", "translit":"I A", "paleocode":"b:b:b_/b:b_a-a:a"},
{"cunei":"𒅆", "codepoint":"U+12146", "translit":"IGI", "borger":"724","paleocode":":w-a-:b"},
{"cunei":"𒅈", "codepoint":"U+12148", "translit":"IGI RI", "borger":"726","paleocode":":w-a-:b_-:b-a-a-:::w-a"},
{"cunei":"𒈥", "codepoint":"U+12225", "translit":"MAR", "borger":"483","paleocode":"b:::b_a-a-:b"},
{"cunei":"𒈪", "codepoint":"U+1222A", "translit":"MI", "borger":"681","paleocode":":W_/b:b:b:b_b:b:b:b"},
{"cunei":"𒈬", "codepoint":"U+1222C", "translit":"MU", "borger":"098","paleocode":"::b-w:w-w:w_w:w"},
{"cunei":"𒉼", "codepoint":"U+1227C", "translit":"PAN", "borger":"685","paleocode":"c_d_c_d"},
{"cunei":"𒊩", "codepoint":"U+122A9", "translit":"SAL", "borger":"883","paleocode":"a::bcb::d"},
{"cunei":"𒊭", "codepoint":"U+122AD", "translit":"ŠA", "borger":"566","paleocode":"b:b:b:b_ac:::d_a"},
{"cunei":"𒊺", "codepoint":"U+122BA", "translit":"ŠE", "borger":"579","paleocode":"W:W-w:w-w:w-w:w-W:W"},
{"cunei":"𒌀", "codepoint":"U+12300", "translit":"TIL", "borger":"114","paleocode":"bc"},
{"cunei":"𒈝", "codepoint":"U+1221D", "translit":"LUM", "borger":"900","paleocode":"c:c:c_d:d:d_c:c:c"},
{"cunei":"𒈣", "codepoint":"U+12223", "translit":"MA2", "borger":"201","paleocode":"Bsa-;b'::sa_a"},
{"cunei":"𒁄", "codepoint":"U+12044", "translit":"BAL", "borger":"005","paleocode":":b-:b_:W-a-:b--/w:w"},
{"cunei":"𒀹", "codepoint":"U+12039", "translit":"AŠ ZIDA tenû", "borger":"575","paleocode":"c"},
{"cunei":"𒀺", "codepoint":"U+1203A", "translit":"AŠ KABA tenû</td><td>647?", "paleocode":"e"},
{"cunei":"𒀼", "codepoint":"U+1203C", "translit":"AŠ / AŠ / AŠ", "borger":"505","paleocode":"b:b:b"},
{"cunei":"𒄧", "codepoint":"U+12127", "translit":"GURUN", "borger":"503","paleocode":"b:::b_a;w-a;w-w:w"},
{"cunei":"𒆦", "codepoint":"U+121A6", "translit":"KISAL", "borger":"435","paleocode":"b:b:b:b_a"},
{"cunei":"𒉒", "codepoint":"U+12252", "translit":"NINDA2", "borger":"316","paleocode":":b:b_a-B;B"},
{"cunei":"𒉺", "codepoint":"U+1227A", "translit":"PA", "borger":"464","paleocode":"b:::b-a"},
{"cunei":"𒉽", "codepoint":"U+1227D", "translit":"PAP", "borger":"092","paleocode":"c:d"},
{"cunei":"𒊬", "codepoint":"U+122AC", "translit":"SAR", "borger":"541","paleocode":":W:W:W-:W:W:W-:W:W:W-a-b;b_a"},
{"cunei":"𒋂", "codepoint":"U+122C2", "translit":"ŠEŠLAM", "borger":"100","paleocode":"c:b-a:a-a:a"},
{"cunei":"𒋃", "codepoint":"U+122C3", "translit":"ŠID", "borger":"485","paleocode":"B:B:B:b-a-a;b_a"},
{"cunei":"𒋖", "codepoint":"U+122D6", "translit":"ŠITA", "borger":"388","paleocode":"A:c;d_A"},
{"cunei":"𒋗", "codepoint":"U+122D7", "translit":"ŠU", "borger":"567","paleocode":"b:b:b:b:b_a"},
{"cunei":"𒍞", "codepoint":"U+1235E", "translit":"ZA tenû", "borger":"854","paleocode":"c.c-c.c"},
{"cunei":"𒍭", "codepoint":"U+1236D", "translit":"ZUBUR", "borger":"648","paleocode":"e:e:e"},
{"cunei":"𒌍", "codepoint":"U+1230D", "translit":"U U U", "borger":"711","paleocode":"W-W-W"},
{"cunei":"𒌋", "codepoint":"U+1230B", "translit":"U", "borger":"661","paleocode":"W"},
{"cunei":"𒋻", "codepoint":"U+122FB", "translit":"TAR", "borger":"009","paleocode":"c.ca"},
{"cunei":"𒋾", "codepoint":"U+122FE", "translit":"TI", "borger":"118","paleocode":":b_:w-a-:b"},
{"cunei":"𒀖", "codepoint":"U+12016", "translit":"AB2", "borger":"672","paleocode":"W-c;d"},
{"cunei":"𒐀", "codepoint":"U+12400", "translit":"two AŠ", "borger":"002","paleocode":"b-b"},
{"cunei":"𒐁", "codepoint":"U+12401", "translit":"three AŠ", "borger":"004","paleocode":"b-b-b"},
{"cunei":"𒐂", "codepoint":"U+12402", "translit":"four AŠ", "borger":"215","paleocode":"b:b_b:b"},
{"cunei":"𒐃", "codepoint":"U+12403", "translit":"five AŠ", "borger":"216","paleocode":"b:b_b:b_b"},
{"cunei":"𒐄", "codepoint":"U+12404", "translit":"six AŠ", "borger":"217","paleocode":"b:b_b:b_b:b"},
{"cunei":"𒐅", "codepoint":"U+12405", "translit":"seven AŠ", "borger":"218","paleocode":"b:b_b:b_b:b_b"},
{"cunei":"𒐆", "codepoint":"U+12406", "translit":"eight AŠ", "borger":"219","paleocode":"b:b_b:b_b:b_b:b"},
{"cunei":"𒐇", "codepoint":"U+12407", "translit":"nine AŠ", "borger":"220","paleocode":"b:b_b:b_b:b_b:b_b"},
{"cunei":"𒐏", "codepoint":"U+1240F", "translit":"four U", "borger":"713","paleocode":"w:w-w:w"},
{"cunei":"𒐐", "codepoint":"U+12410", "translit":"five U", "borger":"714","paleocode":"w:w-w:w-w"},
{"cunei":"𒐑", "codepoint":"U+12411", "translit":"six U", "borger":"715","paleocode":"w:w-w:w-w:w"},
{"cunei":"𒐒", "codepoint":"U+12412", "translit":"seven U", "borger":"716","paleocode":"w:w-w:w-w:w-w"},
{"cunei":"𒐓", "codepoint":"U+12413", "translit":"eight U", "borger":"717","paleocode":"w:w-w:w-w:w-w:w"},
{"cunei":"𒐔", "codepoint":"U+12414", "translit":"nine U", "borger":"718","paleocode":"w:w-w:w-w:w-w:w-w"},
{"cunei":"𒑁", "codepoint":"U+12441", "translit":"IMIN3", "borger":"537","paleocode":"b:b:b_b:b:b_b"},
{"cunei":"𒑆", "codepoint":"U+12446", "translit":"ILIMMU", "borger":"868","paleocode":"a:a:a-a:a:a-a:a:a"},
{"cunei":"𒑈", "codepoint":"U+12448", "translit":"ILIMMU4", "borger":"577","paleocode":"w.w.w"},
{"cunei":"𒑃", "codepoint":"U+12443", "translit":"IMIN variant form", "borger":"866","paleocode":"a:a-a:a-a:a-a"},
{"cunei":"𒑅", "codepoint":"U+12445", "translit":"USSU3", "borger":"538","paleocode":"b:b:b_b:b:b_/b:b"},
{"cunei":"𒑇", "codepoint":"U+12447", "translit":"ILIMMU3", "borger":"539","paleocode":"b:b:b_b:b:b_b:b:b"},
{"cunei":"𒐋", "codepoint":"U+1240B", "translit":"six DIŠ", "borger":"862","paleocode":"a:a-a:a-a:a"},
{"cunei":"𒋥", "codepoint":"U+122E5", "translit":"SUD2", "borger":"139","paleocode":":b_a-a-:b"},
{"cunei":"𒋡", "codepoint":"U+122E1", "translit":"SILA3", "borger":"099","paleocode":"c;d_a"},
{"cunei":"𒄞", "codepoint":"U+1211E", "translit":"GUD", "borger":"472","paleocode":"b:::b_a:c::d"},
{"cunei":"𒃾", "codepoint":"U+120FE", "translit":"GEŠTIN", "borger":"212","paleocode":"b:::b\'::sa-::sa-w:::w-c;d'"},
{"cunei":"𒄾", "codepoint":"U+1213E", "translit":"ḪUL2", "borger":"877","paleocode":"a;w_b:b:b:b-b_a"},
{"cunei":"𒅕", "codepoint":"U+12155", "translit":"IR", "borger":"437","paleocode":"c;d-a-a-a"},
{"cunei":"𒆗", "codepoint":"U+12197", "translit":"KAL", "borger":"496","paleocode":"b:::b-a--a::a"},
{"cunei":"𒆰", "codepoint":"U+121B0", "translit":"KUL", "borger":"117","paleocode":"b-w-b-w:w"},
{"cunei":"𒀝", "codepoint":"U+1201D", "translit":"AK", "borger":"127","paleocode":":W_b:b:b:b--b:b:b:b_a-:bb"},
{"cunei":"𒁳", "codepoint":"U+12073", "translit":"DIB", "borger":"813","paleocode":":a-b::sb:sb::b-::sa--:a"},
{"cunei":"𒐻", "codepoint":"U+1243B", "translit":"EŠ21", "borger":"210","paleocode":"b:b_b"},
{"cunei":"𒑗", "codepoint":"U+12457", "translit":"NIGIDAEŠ", "borger":"850","paleocode":"a:a-a"},
{"cunei":"𒑖", "codepoint":"U+12456", "translit":"NIGIDAMIN", "borger":"847,848","paleocode":"a:a"},
{"cunei":"𒅊", "codepoint":"U+1214A", "translit":"IGI gunû", "borger":"564","paleocode":"b:b:b:b':W_a-:b"},
{"cunei":"𒑙", "codepoint":"U+12459", "translit":"EŠEMIN5 ('BI')", "borger":"359","paleocode":"b:b_w:w"},
{"cunei":"𒆏", "codepoint":"U+1218F", "translit":"KAB", "borger":"148","paleocode":"sb:sb:sb:sb:sb:B-a:::sb-:::w-a"},
{"cunei":"𒆐", "codepoint":"U+12190", "translit":"KAD2", "borger":"108","paleocode":":sbsc-a;w"},
{"cunei":"𒆑", "codepoint":"U+12191", "translit":"KAD3", "borger":"109","paleocode":":sbsc-a;w-a;w-a;w"},
{"cunei":"𒃮", "codepoint":"U+120EE", "translit":"GABA", "paleocode":"b:b_w:w-w:w-w:w-w:w"},
{"cunei":"𒄓", "codepoint":"U+12113", "translit":"GIŠ x BAD", "borger":"471","paleocode":"b:sb-sw:b_a"},
{"cunei":"𒁁", "codepoint":"U+12041", "translit":"BAD", "borger":"113","paleocode":"b_:::sc'sd"},
{"cunei":"𒁀", "codepoint":"U+12040", "translit":"BA", "borger":"014","paleocode":"cd-::b-a"},
{"cunei":"𒁍", "codepoint":"U+1204D", "translit":"BU", "borger":"580","paleocode":"cd_cd_b"},
{"cunei":"𒁎", "codepoint":"U+1204E", "translit":"BU / BU AB", "borger":"582","paleocode":"cd;cd_cd;cd_b:::b_:b:b_;::c'd_a"},
{"cunei":"𒁑", "codepoint":"U+12051", "translit":"BULUG", "borger":"169","paleocode":"b-a;w-bsc_W"},
{"cunei":"𒁓", "codepoint":"U+12053", "translit":"BUR", "borger":"559","paleocode":"b:b:b:b:b_ac;f"},
{"cunei":"𒁔", "codepoint":"U+12054", "translit":"BUR2", "borger":"008","paleocode":":b_ac;d-a_/b--w:w"},
{"cunei":"𒁖", "codepoint":"U+12056", "translit":"DAG", "borger":"438","paleocode":";B-ab.ab.ab.ab-;f'c"},
{"cunei":"𒁮", "codepoint":"U+1206E", "translit":"DAM", "borger":"889","paleocode":"a:bcb::d_a-b:::b-::b--a-::w"},
{"cunei":"𒁲", "codepoint":"U+12072", "translit":"DI", "borger":"736","paleocode":"f;c_-cb:b;f"},
{"cunei":"𒁴", "codepoint":"U+12074", "translit":"DIM", "borger":"167","paleocode":"b_a-aCDcd"},
{"cunei":"𒂖", "codepoint":"U+12096", "translit":"EL", "borger":"899","paleocode":"a:bcb::d_b-;sb'::sa--a"},
{"cunei":"𒂡", "codepoint":"U+120A1", "translit":"EZEN", "borger":"271","paleocode":":sa-:sb::sb-ab;b_a-:sb::sb-:sa"},
{"cunei":"𒂠", "codepoint":"U+120A0", "translit":"EŠ2",  "borger":"810; 811","paleocode":"a-b;B-sb:sb:sb:sb:sb_a"},
{"cunei":"𒂷", "codepoint":"U+120B7", "translit":"GA2", "borger":"387","paleocode":"b;b';sa-;sa--a"},
{"cunei":"𒃷", "codepoint":"U+120F7", "translit":"GAN2", "borger":"174","paleocode":";B';sa-;sa-b;sa-;sa-;sa-a"},
{"cunei":"𒉣", "codepoint":"U+12263", "translit":"NUN", "borger":"143","paleocode":"::B':sa-:sa-:sa-:sa-a"},
{"cunei":"𒃰", "codepoint":"U+120F0", "translit":"GAD", "borger":"157","paleocode":"d;c_A"},
{"cunei":"𒄥", "codepoint":"U+12125", "translit":"GUR", "borger":"180","paleocode":"b:::b-a--a"},
{"cunei":"𒍏", "codepoint":"U+1234F", "codepoint":"URUDU (URUDA)", "borger":"230","paleocode":":sa-:sb::sb-a-b;b_a"},
{"cunei":"𒌝", "codepoint":"U+1231D", "codepoint":"UM", "borger":"238","paleocode":":sb:sb-a-B;B':sa-:sa-:sa-:sa-a"},
{"cunei":"𒃴", "codepoint":"U+120F4", "translit":"GALAM (SUKUD)", "borger":"338","paleocode":":sb:sb-a-c;d_/:w"},
{"cunei":"𒉌", "codepoint":"U+1224C", "translit":"NI", "borger":"380","paleocode":"c;d-;sa-;sa"},
{"cunei":"𒍑", "codepoint":"U+12351", "translit":"UŠ (NITA)", "borger":"381","paleocode":"b;b';sa-;sa-;w-a"},
{"cunei":"𒆤", "codepoint":"U+121A4", "translit":"KID (LÍL)", "borger":"484","paleocode":"b:b:b:b'a-a-a-a-a"},
{"cunei":"𒌒", "codepoint":"U+12312", "translit":"UB", "borger":"504","paleocode":"d;c_;sa'c;d"},
{"cunei":"𒌙", "codepoint":"U+12319", "translit":"UD-gunû", "borger":"542","paleocode":"sb:sb:sb:sb_d;c_a::a"},
{"cunei":"𒇬", "codepoint":"U+121EC", "translit":"LAGAR", "borger":"719","paleocode":"d;c-::sa--A"},
{"cunei":"𒆠", "codepoint":"U+121A0", "translit":"KI", "borger":"737","paleocode":"f;c_-cb:b:b:b::f"},
{"cunei":"𒈨𒌍", "codepoint":"U+12228 &amp; U+1230D ", "translit":"MEŠ", "borger":"754","paleocode":"a-:b_W-W-W"},
{"cunei":"𒍦", "codepoint":"U+12366", "translit":"ZIB", "borger":"628","paleocode":";sc-':::sc-'::sc-:sc"},
{"cunei":"𒍴", "codepoint":"U+12374", "translit":"DAG3", "paleocode":"b::b-::sa-::sa-:::sc:sc--sa::sa"},
{"cunei":"𒀪", "codepoint":"U+1202A", "translit":"aleph", "borger":"635","paleocode":"f;c_-c:b';d"},
{"cunei":"𒅁", "codepoint":"U+12141", "translit":"IB", "borger":"807","paleocode":";B'a-:B':sa-:sa-:sa-:sa-a"},
{"cunei":"𒂽", "codepoint":"U+120BD", "translit":"GÁ×AŠ", "borger":"389","paleocode":"b;b';sa-;sa-::sb-a"},
{"cunei":"𒃢", "codepoint":"U+120E2", "translit":"SILA4 (GÁ×PA)", "borger":"408","paleocode":"b;b\';sa-;sa-:sb:sb-:sa-a"},
{"cunei":"𒁕", "codepoint":"U+12055", "translit":"DA", "borger":"561","paleocode":"B:sb:sb:sb:sb:sb:b--:a-:::sb-:::w-A"},
{"cunei":"𒁷", "codepoint":"U+12077", "translit":"DIN", "borger":"119","paleocode":"W:::W'-c;d"},
{"cunei":"𒀿", "codepoint":"U+1203F", "translit":"AŠGAB", "borger":"173","paleocode":";B'a-:::sa-:::csa-:::sa-:::sa"},
{"cunei":"𒃼", "codepoint":"U+120FC", "translit":"GAR3", "borger":"543","paleocode":"b:b:b:b_Wc;d"},
{"cunei":"𒃿", "codepoint":"U+120FF", "translit":"GEŠTIN x KUR", "borger":"213","paleocode":"b:::b'::sa-::sa-W:::W-c;d':w::w-::w"},
{"cunei":"𒂂", "codepoint":"U+12082", "translit":"DUGUD", "borger":"704","paleocode":"W-:b:b:b:b_b:b:b:b_::/b"},
{"cunei":"𒂅", "codepoint":"U+12085", "translit":"DUN3", "borger":"836","paleocode":"B;b'a--a::b_sa"},
{"cunei":"𒂢", "codepoint":"U+120A2", "translit":"EZEN x A", "borger":"288","paleocode":":sa-:sb::sb-ab;b-:sa-:sa:sa-a-:sb::sb-:sa"},
{"cunei":"𒅅", "codepoint":"U+12145", "translit":"IG", "borger":"136","paleocode":";B-a-b:b:b:b-a-a_:::w:w"},
{"cunei":"𒅂", "codepoint":"U+12142", "translit":"IDIM", "paleocode":"!b:b"},
{"cunei":"𒇺", "codepoint":"U+121FA", "translit":"LIŠ", "borger":"591","paleocode":"sc--a"},
{"cunei":"𒇻", "codepoint":"U+121FB", "translit":"LU", "borger":"812","paleocode":":a-b;b-:::sb::-::sa-a"},
{"cunei":"𒈮", "codepoint":"U+1222E", "translit":"MUG", "borger":"012","paleocode":"b_ac;d-sa"},
{"cunei":"𒄈", "codepoint":"U+12108", "translit":"GIR2", "borger":"006","paleocode":":B-::cd_c;dsa"},
{"cunei":"𒈧", "codepoint":"U+12227", "translit":"MAŠ2", "borger":"130","paleocode":":b-a_;c'd_c;d"},
{"cunei":"𒍣", "codepoint":"U+12363", "translit":"ZI", "borger":"140","paleocode":":B-a-a-W:W-w:w-w:w-w:w-W:W"},
{"cunei":"𒊑", "codepoint":"U+12291", "translit":"RI", "borger":"142","paleocode":":b'a-a-::w-a"},
{"cunei":"𒅔", "codepoint":"U+12154", "translit":"IN", "borger":"261","paleocode":"w:w:w-w:w:w-w:w:w-c;dsa-;sa"},
{"cunei":"𒆒", "codepoint":"U+12192", "translit":"KAD4", "borger":"568","paleocode":"b:b:b:b_a::cd-a;b"},
{"cunei":"𒆸", "codepoint":"U+121B8", "translit":"LAGAB", "borger":"755","paleocode":"a-b;b_a"},
{"cunei":"𒆹", "codepoint":"U+121B9", "translit":"LAGAB x A", "borger":"795","paleocode":"a-b;b-:sa-:sa:sa-a"},
{"cunei":"𒇥", "codepoint":"U+121E5", "translit":"LAGAB x U", "borger":"786","paleocode":"a-b;b'::w_a"},
{"cunei":"𒇧", "codepoint":"U+121E7", "translit":"LAGAB x U + U + U", "borger":"788","paleocode":"a-b;b'::w-::w-::w-a"},
{"cunei":"𒈖", "codepoint":"U+12216", "translit":"LU3", "borger":"555","paleocode":":sb:sb:sb-a-b;b_a:sb:sb:sb"},
{"cunei":"𒆯", "codepoint":"U+121AF", "translit":"KU7", "borger":"171","paleocode":"b:::b_d;c_a::a"},
{"cunei":"𒄘", "codepoint":"U+12118", "translit":"GU2", "borger":"176", "paleocode":"b:::b-::sa--d;c_::a'c;d"},
{"cunei":"𒋛", "codepoint":"U+122DB", "translit":"SI", "borger":"181","paleocode":"B-;b'::sa_a"},
{"cunei":"𒋜", "codepoint":"U+122DC", "translit":"SU4", "borger":"182", "paleocode":"B-;b'::sa--:sb:sb:sb-a"},
{"cunei":"𒊕", "codepoint":"U+12295", "translit":"SAG", "borger":"184","paleocode":"d;c-::a_a:b::b_a"},
{"cunei":"𒌉", "codepoint":"U+12309", "translit":"TUR", "borger":"255", "paleocode":"a#:sc::scsd::sd--#:b:b"},
{"cunei":"𒊐", "codepoint":"U+12290", "translit":"RAB", "borger":"262", "paleocode":"::b:b-sb:sb:sb_/b::/b-/sb::sa-/sb"},
{"cunei":"𒌫", "codepoint":"U+1232B", "translit":"UR2", "borger":"341","paleocode":"sa-b::b_;c::c_;b:::b_;a"},
{"cunei":"𒁉", "codepoint":"U+12049", "translit":"BI", "borger":"358","paleocode":"b;bsa-;sa_c;ad-a"},
{"cunei":"𒑊", "codepoint":"U+1244A", "translit":"TAB variant old", "borger":"593","paleocode":":::sc-'::sc"},
{"cunei":"𒑢", "codepoint":"U+12462", "translit":"Number 1/4(Kültepe)", "borger":"594","paleocode":":::sc-'::sc-::b-:b"},
{"cunei":"𒌌", "codepoint":"U+1230C", "codepoint":"UL", "borger":"698", "paleocode":"W_b::b_ac;d"},
{"cunei":"𒎙", "codepoint":"U+12399", "translit":"MAN", "borger":"708", "paleocode":"W-W"},
{"cunei":"𒊔", "codepoint":"U+12294", "translit":"KIŠI4", "borger":"743","paleocode":"d;c_a-:b::b_a"},
{"cunei":"𒍮", "codepoint":"U+1236E", "translit":"ZUM", "borger":"884","paleocode":"Ac::b::d_d:d;c:c"}]
