var sumerian_pat={
    "pattern": [
        {
            "postag": "NE",
            "person": "",
            "number": " ",
            "wordcase": "http://purl.org/olia/olia.owl#Stem",
            "voice": "",
            "animacy": "",
            "tense": "",
            "mood": "",
            "transsuffix": "",
            "pattern": "~",
            "transprefix": "",
            "representation": "transliteration"
        },
        {
            "postag": "NE",
            "person": "",
            "number": "http://purl.org/olia/olia.owl#Singular",
            "wordcase": "http://purl.org/olia/olia.owl#Genitive",
            "animacy": "",
            "tense": "",
            "mood": "",
            "voice": "",
            "transsuffix": "",
            "pattern": "~-ak",
            "transprefix": "of",
            "representation": "transliteration"
        },
        {
            "postag": "NN",
            "person": " ",
            "number": " ",
            "wordcase": "http://purl.org/olia/olia.owl#Stem",
            "animacy": " ",
            "tense": "",
            "mood": "",
            "voice": "",
            "transsuffix": "",
            "pattern": "~",
            "transprefix": "",
            "representation": "transliteration"
        },
        {
            "postag": "NN",
            "person": " ",
            "gender": "http://purl.org/olia/olia.owl#Female",
            "number": "http://purl.org/olia/olia.owl#Singular",
            "wordcase": "http://purl.org/olia/olia.owl#Nominative",
            "animacy": "http://purl.org/olia/olia.owl#Animate",
            "tense": "",
            "mood": "",
            "voice": "",
            "transsuffix": "",
            "pattern": "~-at",   
            "scriptpattern":"~𒀜",
            "transprefix": "",
            "representation": "transliteration"
        },
        {
            "postag": "NN",
            "person": " ",
            "number": "http://purl.org/olia/olia.owl#Singular",
            "wordcase": "http://purl.org/olia/olia.owl#Nominative",
            "animacy": "http://purl.org/olia/olia.owl#Animate",
            "tense": "",
            "mood": "",
            "voice": "",
            "transsuffix": "",
            "pattern": "~-um",   
            "scriptpattern":"~𒌝",
            "transprefix": "",
            "representation": "transliteration"
        },
        {
            "postag": "NN",
            "person": " ",
            "number": "http://purl.org/olia/olia.owl#Singular",
            "wordcase": "http://purl.org/olia/olia.owl#Genitive",
            "animacy": "http://purl.org/olia/olia.owl#Animate",
            "tense": "",
            "mood": "",
            "voice": "",
            "transsuffix": "",
            "pattern": "~-im",   
            "scriptpattern":"~𒅎",
            "transprefix": "",
            "representation": "transliteration"
        },
        {
            "postag": "NN",
            "person": " ",
            "number": "http://purl.org/olia/olia.owl#Singular",
            "wordcase": "http://purl.org/olia/olia.owl#Accusative",
            "animacy": "http://purl.org/olia/olia.owl#Animate",
            "tense": "",
            "mood": "",
            "voice": "",
            "transsuffix": "",
            "pattern": "~-am",   
            "scriptpattern":"~𒄠",
            "transprefix": "",
            "representation": "transliteration"
        }
    ]
}
