var sumerian_pat={
    "pattern": [
        {
            "postag": "NE",
            "person": "",
            "number": " ",
            "wordcase": "http://purl.org/olia/olia.owl#Stem",
            "voice": "",
            "animacy": "",
            "tense": "",
            "mood": "",
            "transsuffix": "",
            "pattern": "~",
            "transprefix": "",
            "representation": "transliteration"
        },
        {
            "postag": "NE",
            "person": "",
            "number": "http://purl.org/olia/olia.owl#Singular",
            "wordcase": "http://purl.org/olia/olia.owl#Genitive",
            "animacy": "",
            "tense": "",
            "mood": "",
            "voice": "",
            "transsuffix": "",
            "pattern": "~-ak",
            "transprefix": "of",
            "representation": "transliteration"
        },
        {
            "postag": "NN",
            "person": " ",
            "number": " ",
            "wordcase": "http://purl.org/olia/olia.owl#Stem",
            "animacy": " ",
            "tense": "",
            "mood": "",
            "voice": "",
            "transsuffix": "",
            "pattern": "~",
            "transprefix": "",
            "representation": "transliteration"
        },
        {
            "postag": "NN",
            "person": " ",
            "number": "http://purl.org/olia/olia.owl#Singular",
            "wordcase": "http://purl.org/olia/olia.owl#Genitive",
            "animacy": "http://purl.org/olia/olia.owl#Animate",
            "tense": "",
            "mood": "",
            "voice": "",
            "transsuffix": "",
            "pattern": "~-ak",   
            "scriptpattern":"~𒀝",
            "transprefix": "of",
            "representation": "transliteration"
        },{
            "postag": "NN",
            "person": " ",
            "number": "http://purl.org/olia/olia.owl#Singular",
            "wordcase": "http://purl.org/olia/olia.owl#Terminative",
            "animacy": "http://purl.org/olia/olia.owl#Animate",
            "tense": "",
            "mood": "",
            "voice": "",
            "transsuffix": "",
            "pattern": "~-sze3",   
            "scriptpattern":"~𒂠",
            "transprefix": "finally",
            "representation": "transliteration"
        },
        {
            "postag": "NN",
            "person": " ",
            "number": "http://purl.org/olia/olia.owl#Singular",
            "wordcase": "http://purl.org/olia/olia.owl#Dative",
            "animacy": "http://purl.org/olia/olia.owl#Animate",
            "tense": "",
            "mood": "",
            "voice": "",
            "transsuffix": "",
            "pattern": "~-ra",   
            "scriptpattern":"~𒊏",
            "transprefix": "to",
            "representation": "transliteration"
        },
        {
            "postag": "NN",
            "person": " ",
            "number": "http://purl.org/olia/olia.owl#Singular",
            "wordcase": "http://purl.org/olia/olia.owl#Locative",
            "animacy": "http://purl.org/olia/olia.owl#Animate",
            "tense": "",
            "mood": "",
            "voice": "",
            "transsuffix": "",
            "pattern": "~-bi",   
            "scriptpattern":"~𒁉",
            "transprefix": "at",
            "representation": "transliteration"
        },
        {
            "postag": "NN",
            "person": " ",
            "number": "http://purl.org/olia/olia.owl#Plural",
            "wordcase": "http://purl.org/olia/olia.owl#Nominative",
            "animacy": "http://purl.org/olia/olia.owl#Animate",
            "tense": "",
            "mood": "",
            "voice": "",
            "transsuffix": "s",
            "pattern": "~-e-ne",
            "scriptpattern":"~𒂊𒉈",
            "transprefix": "",
            "representation": "transliteration"
        },
        {
            "postag": "NN",
            "person": "http://purl.org/olia/olia.owl#First",
            "number": "http://purl.org/olia/olia.owl#Singular",
            "wordcase": "http://purl.org/olia/olia.owl#Possessive",
            "animacy": "http://purl.org/olia/olia.owl#Animate",
            "tense": "",
            "mood": "",
            "voice": "",
            "transsuffix": "",
            "pattern": "~-ju",
            "scriptpattern":"~𒄖",
            "transprefix": "my",
            "representation": "transliteration"
        },
        {
            "postag": "NN",
            "person": "http://purl.org/olia/olia.owl#Second",
            "number": "http://purl.org/olia/olia.owl#Singular",
            "wordcase": "http://purl.org/olia/olia.owl#Possessive",
            "animacy": "http://purl.org/olia/olia.owl#Animate",
            "tense": "",
            "mood": "",
            "voice": "",
            "transsuffix": "",
            "pattern": "~-zu",
            "scriptpattern":"~𒍪",
            "transprefix": "your",
            "representation": "transliteration"
        },
        {
            "postag": "NN",
            "person": "http://purl.org/olia/olia.owl#Third",
            "number": "http://purl.org/olia/olia.owl#Singular",
            "wordcase": "http://purl.org/olia/olia.owl#Possessive",
            "animacy": "http://purl.org/olia/olia.owl#Animate",
            "tense": "",
            "mood": "",
            "voice": "",
            "transsuffix": "",
            "pattern": "~-a-ni",
            "scriptpattern": "~𒀀𒉌",
            "transprefix": "his/her",
            "representation": "transliteration"
        },
        {
            "postag": "NN",
            "person": "http://purl.org/olia/olia.owl#Third",
            "number": "http://purl.org/olia/olia.owl#Singular",
            "wordcase": "http://purl.org/olia/olia.owl#Possessive",
            "animacy": "http://purl.org/olia/olia.owl#Inanimate",
            "tense": "",
            "mood": "",
            "voice": "",
            "transsuffix": "",
            "pattern": "~-bi",
            "scriptpattern":"~𒁉",
            "transprefix": "its",
            "representation": "transliteration"
        },
        {
            "postag": "NN",
            "person": "http://purl.org/olia/olia.owl#First",
            "number": "http://purl.org/olia/olia.owl#Plural",
            "wordcase": "http://purl.org/olia/olia.owl#Possessive",
            "animacy": "http://purl.org/olia/olia.owl#Animate",
            "tense": "",
            "mood": "",
            "voice": "",
            "transsuffix": "",
            "pattern": "~-me",     
            "scriptpattern": "~𒈨",    
            "transprefix": "our",
            "representation": "transliteration"
        },
        {
            "postag": "NN",
            "person": "http://purl.org/olia/olia.owl#Second",
            "number": "http://purl.org/olia/olia.owl#Plural",
            "wordcase": "http://purl.org/olia/olia.owl#Possessive",
            "animacy": "http://purl.org/olia/olia.owl#Animate",
            "tense": "",
            "mood": "",
            "voice": "",
            "transsuffix": "",
            "pattern": "~-zu-ne-ne",
            "scriptpattern":"~𒍪𒉈𒉈",
            "transprefix": "your",
            "representation": "transliteration"
        },
        {
            "postag": "NN",
            "person": "http://purl.org/olia/olia.owl#Third",
            "number": "http://purl.org/olia/olia.owl#Plural",
            "wordcase": "http://purl.org/olia/olia.owl#Possessive",
            "animacy": "http://purl.org/olia/olia.owl#Animate",
            "tense": "",
            "mood": "",
            "voice": "",
            "transsuffix": "",
            "pattern": "~-a-ne-ne",
            "scriptpattern":"~𒀀𒉈𒉈",
            "transprefix": "their",
            "representation": "transliteration"
        },
        {
            "postag": "VV",
            "person": "",
            "number": " ",
            "wordcase": "http://purl.org/olia/olia.owl#Stem",
            "animacy": "",
            "tense": " ",
            "mood": "",
            "voice": "",
            "transsuffix": "",
            "pattern": "~",
            "scriptpattern": "~",
            "transprefix": "",
            "representation": "transliteration"
        },
        {
            "postag": "VV",
            "person": "http://purl.org/olia/olia.owl#First",
            "number": "http://purl.org/olia/olia.owl#Singular",
            "wordcase": "",
            "animacy": "",
            "tense": "http://purl.org/olia/olia.owl#Present",
            "mood": "",
            "voice": "",
            "transsuffix": "",
            "pattern": "~-men",            
            "transprefix": "I",
            "representation": "transliteration"
        },
                {
            "postag": "VV",
            "person": "http://purl.org/olia/olia.owl#Second",
            "number": "http://purl.org/olia/olia.owl#Singular",
            "wordcase": "",
            "animacy": "",
            "tense": "http://purl.org/olia/olia.owl#Present",
            "mood": "",
            "voice": "",
            "transsuffix": "",
            "pattern": "~-men",
            "scriptpattern":"~𒃞",
            "transprefix": "you",
            "representation": "transliteration"
        },
                {
            "postag": "VV",
            "person": "http://purl.org/olia/olia.owl#Third",
            "number": "http://purl.org/olia/olia.owl#Singular",
            "wordcase": "",
            "animacy": "",
            "tense": "http://purl.org/olia/olia.owl#Present",
            "mood": "",
            "voice": "",
            "transsuffix": "s",
            "pattern": "~-me-am",
            "scriptpattern":"~𒈨𒄠",
            "transprefix": "he/she",
            "representation": "transliteration"
        },
        {
            "postag": "VV",
            "person": "http://purl.org/olia/olia.owl#First",
            "number": "http://purl.org/olia/olia.owl#Plural",
            "wordcase": "",
            "animacy": "",
            "tense": "http://purl.org/olia/olia.owl#Present",
            "mood": "",
            "voice": "",
            "transsuffix": "",
            "pattern": "~-men-den",
            "transprefix": "we",
            "representation": "transliteration"
        },
        {
            "postag": "VV",
            "person": "http://purl.org/olia/olia.owl#Second",
            "number": "http://purl.org/olia/olia.owl#Plural",
            "wordcase": "",
            "animacy": "",
            "tense": "http://purl.org/olia/olia.owl#Present",
            "mood": "",
            "voice": "",
            "transsuffix": "",
            "pattern": "~-men-zen",
            "transprefix": "you",
            "representation": "transliteration"
        },
        {
            "postag": "VV",
            "person": "http://purl.org/olia/olia.owl#Third",
            "number": "http://purl.org/olia/olia.owl#Plural",
            "wordcase": "",
            "animacy": "",
            "tense": "http://purl.org/olia/olia.owl#Present",
            "mood": "",
            "voice": "",
            "transsuffix": "",
            "pattern": "~-mesz",
            "scriptpattern":"𒌊",
            "transprefix": "they",
            "representation": "transliteration"
        },
                {
            "postag": "VV",
            "person": "http://purl.org/olia/olia.owl#First",
            "number": "http://purl.org/olia/olia.owl#Singular",
            "wordcase": "http://purl.org/olia/olia.owl#Ventive",
            "animacy": "",
            "tense": "http://purl.org/olia/olia.owl#Present",
            "mood": "",
            "voice": "",
            "transsuffix": " here ",
            "pattern": "mu~", 
            "scriptpattern": "𒈬~",  
            "transprefix": "I",
            "representation": "transliteration"
        },
                      {
            "postag": "VV",
            "person": "http://purl.org/olia/olia.owl#First",
            "number": "http://purl.org/olia/olia.owl#Singular",
            "wordcase": "http://purl.org/olia/olia.owl#Optative",
            "animacy": "",
            "tense": "http://purl.org/olia/olia.owl#Present",
            "mood": "",
            "voice": "",
            "transsuffix": "",
            "pattern": "ha~", 
            "scriptpattern": "𒄩~",  
            "transprefix": "I wish to ",
            "representation": "transliteration"
        }
    ]
}
